### ISSUE TITLE
RIFE model source?

### ISSUE THREAD

**Issue by couleurm** [AmusementClub/tools#2]
Hi, where do you get these from? Thank you
![image](https://user-images.githubusercontent.com/82747632/231152549-2a6698cc-fe9b-4d73-97c9-075064e20b2e.png)

**Comment by dtlnor** [comment]
> Hi, where do you get these from? Thank you
> 
> ![image](https://user-images.githubusercontent.com/82747632/231152549-2a6698cc-fe9b-4d73-97c9-075064e20b2e.png)
> 
> 

from vs-mlrt
https://github.com/AmusementClub/vs-mlrt
